CREATE TABLE musics(
    id BIGINT AUTO_INCREMENT PRIMARY KEY, 
    uuid BINARY(16) NOT NULL UNIQUE, 
    playlist_id BIGINT NOT NULL
    name VARCHAR(255) NOT NULL, 
    path VARCHAR(500) NOT NULL, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

    FOREING KEY (playlist_id) REFERENCES playlists(id)
)